### ISSUE TITLE
HR straps

### ISSUE THREAD

**Issue by AdrienLemaire** [vtrifonov-esfiddle/TestHrv#4]
Why aren't HR straps supported? They are usually more precise than the wrist watch, and precision matters for a sensitive calculation like HRV

**Comment by vtrifonov-esfiddle** [comment]
HR straps are not supported because I do not have one and if a user reports a bug related to an HR strap problem I won't be able to reproduce it. You should be able to use HR strap with the app though. Make sure you configure it from your watch before starting the app. Then the measurements should come from the strap.

**Comment by filipsPL** [comment]
I confirm that HR Straps are supported "natively". Just put on your strap and run the test.

**Comment by llaumgui** [comment]
Hi,

why not edit the README ?

"HR straps not supported" => "HR straps seem work but not supported by author".
